print('a.x²= b.x + c')
a=int(input('Escolha o valor para a: '))
b=int(input('Escolha o valor para b: '))
c=int(input('Escolha o valor para c: '))
print('{}.x²+({}).x +({})'.format(a,b,c))
delta=b**2-4*a*c
print('delta = b²-4*a*c')
print('delta = ({})²-4*({})*({})'.format(b,a,c))
print('delta=', delta)
if delta<0:
    print("Delta não possui valor Real")
if delta==0:
    print("A equação só possui um unico valor Real")
    print('x1=(-b/(2*a)')
    print('x1=(-({})/(2*{})'.format(b,a))
    x1=-b/(2*a)
    print('x1=',x1)
if delta>0:
    print('A equação possui duas raizes Reais')
    print('x1=(-b+delta**(1/2)/(2*a)')
    print('x1=(-({})+{}**(1/2)/(2*{})'.format(b,delta,a))
    x1=(-b+delta**(1/2))/(2*a)
    print('x1=',x1)
    print('x2=(-b-delta**(1/2))/(2*a)')
    print('x2=(-({})-{}**(1/2)/(2*{})'.format(b,delta,a))
    x2=(-b-delta**(1/2))/(2*a)
    print('x2=',x2)